services:
  {{ cookiecutter.project_slug }}:
    env_file:
      - .env
    environment:
      - ENV_NAME=prod
    image: '{{cookiecutter.project_slug}}:latest'
    build:
      context: .
    tty: true
